# Generated by Django 4.2.7 on 2025-11-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instances", "0003_populate_default_qr_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Mark this instance as the demo instance for the landing page",
            ),
        ),
    ]
