# Generated by Django 4.2.7 on 2025-11-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0005_add_menu_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="Mark this menu as the demo menu for the landing page",
            ),
        ),
    ]
