# Generated by Django 4.2.7 on 2025-11-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menus", "0006_menu_is_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="schedule",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Menu activation schedule: {enabled: bool, startTime: str, endTime: str, days: []}",
            ),
        ),
    ]
